#!/bin/sh

git clone --depth=1 https://github.com/LPGhatguy/lemur.git modules/lemur
cp -r modules/lemur/src/lemur .
rm -rf modules/lemur

git clone --depth=1 https://github.com/Roblox/TestEZ.git modules/testez
cp -r modules/testez/src/testez .
rm -rf modules/testez